name: Rust build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain (v1.80.0)
        uses: dtolnay/rust-toolchain@1.80.0
      - name: Run build
        run: cargo build
      - name: Run test
        run: cargo test
